export const refs = {
  musclesFilter: document.querySelector('[data-filterRequset="Muscles"]'),
  bodyPartsFilter: document.querySelector('[data-filterRequset="Body parts"]'),
  equipmentFilter: document.querySelector('[data-filterRequset="Equipment"]'),
  inputHolder: document.querySelector('.filter__searchBox'),
  inputField: document.querySelector('.filter__searchBox__input'),
  filterList: document.querySelector('.filter__list'),
  specialSign: document.querySelector('.filter__query__specialSign'),
  specialText: document.querySelector('.filter__query'),
  noData: document.querySelector('.error-block'),
  paginationContainer: document.querySelector('.pagination__container'),
  searchIcon: document.querySelector('.js-search'),
  closeIcon: document.querySelector('.js-close'),
  searchBtn: document.querySelector('.filter__searchBox__btn'),
};
